[package]
name = "ray_tracing_in_one_week_rust"
version = "0.1.0"
authors = ["Hyiker Hu <hyiker@bupt.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
num = "0.3.0"
num_cpus = "1.13.0"